version: "3"
services:
  java:
    build:
      context: .
      dockerfile: docker/dockerfile-java
    volumes:
       - ./:/code
    working_dir: /code
    command: tail -f /dev/null
    tty: true
  script:
    build:
      context: .
      dockerfile: docker/dockerfile-script
    volumes:
       - ./:/code
    working_dir: /code
    command: tail -f /dev/null
    tty: true
  tomcat:
    image: "tomcat:8-jre8"
    volumes:
      - ./:/code
    ports:
      - "8080:8080"
  postgres:
    image: "postgres:9.5"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
